# Generated by Django 5.0.7 on 2024-08-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(max_length=50)),
                ('loan_id', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Loan Repayment'), (3, 'Interest'), (4, 'Fines')], max_length=5)),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
