# Generated by Django 5.0.7 on 2024-08-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Loan Repayment'), (3, 'Interest'), (4, 'Fines')]),
        ),
    ]
