# Generated by Django 5.0.7 on 2024-08-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('repaid', 'Repaid')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
    ]
