# Generated by Django 5.0.7 on 2024-08-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loans', '0002_loan_delete_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='comments',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loan',
            name='ref_no',
            field=models.CharField(default='Unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='repaid',
            field=models.CharField(choices=[(0, 'Yes'), (1, 'No')], default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='loan',
            name='repaid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], max_length=10),
        ),
    ]
