# Generated by Django 5.0.7 on 2024-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='join_date',
            new_name='joining_date',
        ),
        migrations.AddField(
            model_name='member',
            name='id_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.CharField(choices=[(0, 'Yes'), (1, 'No')], default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='is_staff',
            field=models.CharField(choices=[(0, 'Yes'), (1, 'No')], default=1, max_length=5),
        ),
        migrations.AddField(
            model_name='member',
            name='profession',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
    ]
