# Generated by Django 5.0.7 on 2024-08-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_rename_join_date_member_joining_date_member_id_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField()),
                ('account_number', models.IntegerField(max_length=10)),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_type', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1, max_length=5)),
            ],
        ),
    ]
