# Generated by Django 5.0.7 on 2024-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0005_alter_account_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_active',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_staff',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1),
        ),
    ]
